# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPipeLine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPipeLine

  target 'TestPipeLineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestPipeLineUITests' do
    # Pods for testing
  end

end
